# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 07d71b8a8719d2a6186a777fc2f750d80dfaa4a2677546e7ccb616a02efa5aed9c1c82ce679e22e2965db769ac033fd07821274eda627bbeb925c19a1c116b12

test:
  secret_key_base: 460c56e389dd64bab17d476a1ead7108be1996378d7394d190e47bb50420a51e6b0614b1f3efcee02affe9eff3035050e22ab2e636bf747f51d798560356315a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>

staging:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
